version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1 #the primary container where the jobs are run
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command